server:
  port: 8765

spring:
  application:
    name: zuul

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

zuul:
  routes:
    evento: /evento/**
    Usuarios: /user/**
    notificacion: /notificacion/**
    webapp: /webapp/**

logging:
  level:
    org: INFO
    ROOT: INFO